### ISSUE TITLE
Errors when connecting to openvidu server.

### ISSUE THREAD

**Issue by t3mnikov** [Stopka/openvidu-php-client#1]
Hi, Štěpán!
I'm using your extension. 
```
 $openVidu = new OpenVidu('https://localhost:4443/', 'MY_SECRET');
 $openVidu->enableSslCheck(false);
 $sessionId = $openVidu->createSession()->getSessionId();
```
When connecting to openvidu server I get errors:
`SSL certificate problem: unable to get local issuer certificate`
or
`SSL certificate problem: self signed certificate`

 How should my local machine be properly configured?
 Thanks

**Comment by t3mnikov** [comment]
Code error!  Create the Http instance occurs prior to calling OpenVidu::enableSslCheck(false). Fix yourself. Now another question. Is it safe to disable certificate validation if I have opnvidu and kms on the same server?
Thanks a lot for your extension!

**Comment by Stopka** [comment]
THX. I need to write unit test. Will fix it.

Option OpenVidu::enableSslCheck(false) is meant for testing purposes only and it disables ssl check only on connection php server-openvidu server. It has no effect on connection openvidu-kms and others.
